version: '3.9'

services:

    centos7:
        image: centos7-systemd-sshd:latest
        build:
            context: .
            args:
                USER_NAME: "user"
                USER_PASSWD: "password"
        ports:
            - "2222:22"
        cap_add:
            - SYS_ADMIN
#        volumes:
#            - /sys/fs/cgroup:/sys/fs/cgroup:rw
        # restart: always

